# name: "Publish on NPM"
# on:
#   workflow_dispatch:
#   push:
#     tags-ignore:
#       - "*.*"
#     branches:
#       - main
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     if: github.actor != 'prisma-bot' # Prevents an infinite job loop
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.GH_PAT }}
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "16"
#       - name: Install dependencies
#         run: pnpm install
#       - name: "Publish to NPM: Patch"
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           GH_PAT: ${{ secrets.GH_PAT }}
#         run: |
#           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#           echo "Logged into NPM as: $(npm whoami)"
#           git config --global user.name "Prismo"
#           git config --global user.email "<>"
#           pnpm changeset version
#           pnpm -r publish
#           git push https://$PRISMO_PAT@github.com/prisma/lens.git --follow-tags
